In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('cancer.csv')

In [4]:
df.head()

,id,clump_thickness,unif_cell_size,unif_cell_shape,marg_adhesion,single_epith_cell_size,bare_nuclei,bland_chrom,norm_nucleoli,mitoses,classes
0,1000025,5,1,1,1,2,1,3,1,1,0
1,1002945,5,4,4,5,7,10,3,2,1,0
2,1015425,3,1,1,1,2,2,3,1,1,0
3,1016277,6,8,8,1,3,4,3,7,1,0
4,1017023,4,1,1,3,2,1,3,1,1,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      699 non-null    int64
 1   clump_thickness         699 non-null    int64
 2   unif_cell_size          699 non-null    int64
 3   unif_cell_shape         699 non-null    int64
 4   marg_adhesion           699 non-null    int64
 5   single_epith_cell_size  699 non-null    int64
 6   bare_nuclei             699 non-null    object
 7   bland_chrom             699 non-null    int64
 8   norm_nucleoli           699 non-null    int64
 9   mitoses                 699 non-null    int64
 10  classes                 699 non-null    int64
dtypes: int64(10), object(1)
memory usage: 60.2+ KB

In [6]:
df.describe()

,id,clump_thickness,unif_cell_size,unif_cell_shape,marg_adhesion,single_epith_cell_size,bland_chrom,norm_nucleoli,mitoses,classes
count,6.990000e+02,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000
mean,1.071704e+06,4.417740,3.134478,3.207439,2.806867,3.216023,3.437768,2.866953,1.589413,0.344778
std,6.170957e+05,2.815741,3.051459,2.971913,2.855379,2.214300,2.438364,3.053634,1.715078,0.475636
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,8.706885e+05,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,0.000000
50%,1.171710e+06,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,0.000000
75%,1.238298e+06,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,1.000000,1.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000

In [4]:
df.replace('?',-99999,inplace=True)

In [5]:
df.drop(['id'],1,inplace=True)

In [6]:
df.head()

,clump_thickness,unif_cell_size,unif_cell_shape,marg_adhesion,single_epith_cell_size,bare_nuclei,bland_chrom,norm_nucleoli,mitoses,classes
0,5,1,1,1,2,1,3,1,1,0
1,5,4,4,5,7,10,3,2,1,0
2,3,1,1,1,2,2,3,1,1,0
3,6,8,8,1,3,4,3,7,1,0
4,4,1,1,3,2,1,3,1,1,0

In [7]:
X=np.array(df.drop(['classes'],1))
y=np.array(df['classes'])

In [8]:
X

array([[5, 1, 1, ..., 3, 1, 1],
       [5, 4, 4, ..., 3, 2, 1],
       [3, 1, 1, ..., 3, 1, 1],
       ...,
       [5, 10, 10, ..., 8, 10, 2],
       [4, 8, 6, ..., 10, 6, 1],
       [4, 8, 8, ..., 10, 4, 1]], dtype=object)

In [9]:
y

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
X_train

array([[-1.19480731, -0.70594093, -0.74391107, ..., -0.17105851,
        -0.60754169, -0.35584471],
       [-0.49527767, -0.70594093, -0.74391107, ..., -0.58796391,
        -0.60754169, -0.35584471],
       [ 0.20425198, -0.70594093, -0.74391107, ..., -1.00486931,
        -0.60754169, -0.35584471],
       ...,
       [-0.14551285,  1.61222498,  0.93052793, ...,  1.49656308,
        -0.60754169, -0.35584471],
       [-0.84504249, -0.70594093, -0.74391107, ..., -0.58796391,
        -0.60754169, -0.35584471],
       [ 0.20425198,  2.27455809,  2.27007913, ...,  2.74727927,
         1.0100998 ,  1.77515675]])

In [13]:
X_test

array([[-0.14551285, -0.70594093, -0.74391107, ..., -1.00486931,
        -0.60754169, -0.35584471],
       [-0.84504249, -0.70594093, -0.74391107, ..., -0.17105851,
        -0.60754169, -0.35584471],
       [ 1.95307608,  2.27455809,  0.93052793, ...,  0.24584688,
         0.03951491,  0.17690566],
       ...,
       [-0.14551285, -0.70594093, -0.74391107, ..., -1.00486931,
        -0.28401339, -0.35584471],
       [-0.49527767, -0.70594093, -0.74391107, ..., -0.58796391,
        -0.60754169, -0.35584471],
       [-0.49527767, -0.70594093, -0.74391107, ..., -1.00486931,
        -0.60754169, -0.35584471]])

In [14]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)
explained_variance=pca.explained_variance_ratio_

In [15]:
X_train

array([[-1.7507631 , -0.13706882],
       [-1.6798227 , -0.15154471],
       [-1.6088823 , -0.1660206 ],
       ...,
       [ 1.34855718,  0.01536871],
       [-1.78983662, -0.15713299],
       [ 5.19752268, -0.04178352]])

In [16]:
X_test

array([[-1.58582877e+00, -8.11540681e-01],
       [-1.46012087e+00, -7.55803438e-01],
       [ 2.14155665e+00, -3.40757018e-02],
       [ 2.59176002e+00,  2.07740074e-01],
       [-1.22129906e+00, -7.12546156e-01],
       [-1.41489186e+00, -7.75200538e-01],
       [-1.53656186e+00, -7.72687931e-01],
       [ 2.40251594e+00,  7.54517325e-02],
       [-3.43645470e+00,  7.72182064e+00],
       [ 4.05965033e+00,  4.35368619e-01],
       [-1.60762070e+00, -7.90836264e-01],
       [ 2.92174475e+00,  1.30877046e-01],
       [ 7.12822046e-01,  8.69077857e+00],
       [-1.20220609e+00, -7.33008338e-01],
       [-2.23158182e+00,  7.97351537e+00],
       [-1.69383940e+00, -8.20352237e-01],
       [-3.69867743e+00,  7.67708602e+00],
       [-1.52297482e+00, -7.83672060e-01],
       [ 2.86206111e+00,  1.41741501e-01],
       [ 2.94071631e+00,  2.05669727e-01],
       [-1.47766304e+00, -7.31043583e-01],
       [ 3.23745455e+00,  2.98566211e-01],
       [ 3.88203962e+00,  4.26695314e-01],
       [-1.71941422e+00, -7.87419459e-01],
       [ 1.51588914e-01, -4.08626863e-01],
       [-1.13935214e+00, -7.05139716e-01],
       [ 3.18951588e+00,  2.48418904e-01],
       [ 3.13073502e+00,  1.75729006e-01],
       [-1.56820383e+00, -7.64274959e-01],
       [ 9.04490775e-01, -2.58980860e-01],
       [-1.35200174e+00, -7.47501933e-01],
       [-1.67418521e+00, -8.06816559e-01],
       [ 1.59808520e+00, -9.67228221e-02],
       [ 1.94977078e+00, -1.18944016e-01],
       [ 4.32181537e+00,  5.10265178e-01],
       [-1.56820383e+00, -7.64274959e-01],
       [-1.58582877e+00, -8.11540681e-01],
       [ 7.05107242e-01, -3.33410074e-01],
       [-1.69391173e+00, -8.20012203e-01],
       [ 3.37794996e+00,  2.03831198e-01],
       [-1.32938202e+00, -7.21017678e-01],
       [ 3.83982580e+00,  2.62187057e-01],
       [-1.28191437e+00, -7.51900003e-01],
       [-6.21639640e-01, -6.92115095e-01],
       [-1.91007765e+00, -8.36955246e-01],
       [-5.62242401e-01, -6.74092467e-01],
       [-1.69391173e+00, -8.20012203e-01],
       [-1.13587199e+00, -7.30388873e-01],
       [-1.47984739e+00, -7.68999082e-01],
       [ 6.85971551e-01, -4.13591862e-01],
       [ 3.13249238e+00,  2.24089483e-01],
       [-5.82672647e-01, -6.04431168e-01],
       [-1.56610225e+00, -7.98345038e-01],
       [ 5.62651201e+00,  7.19981224e-01],
       [-2.06128804e+00, -8.60099746e-01],
       [ 2.28382743e+00, -4.13609298e-02],
       [-1.47774581e+00, -8.03069160e-01],
       [-1.52297482e+00, -7.83672060e-01],
       [ 3.92772376e+00,  3.39488117e-01],
       [-1.41866502e+00, -7.51754946e-01],
       [ 1.59032453e+00,  8.78388782e+00],
       [-1.73914074e+00, -8.00615103e-01],
       [ 1.93426937e+00, -1.57865918e-01],
       [-1.25701983e+00, -7.37070989e-01],
       [ 1.85284101e-01, -3.88693777e-01],
       [-1.52297482e+00, -7.83672060e-01],
       [-1.13587199e+00, -7.30388873e-01],
       [-1.46012087e+00, -7.55803438e-01],
       [-3.28598933e+00,  7.76980204e+00],
       [ 4.76580028e+00,  4.86391856e-01],
       [-1.32504180e+00, -7.66572981e-01],
       [-1.52297482e+00, -7.83672060e-01],
       [-1.56804108e+00, -7.65040036e-01],
       [-3.54746704e+00,  7.70023052e+00],
       [-1.37176443e+00, -7.60527560e-01],
       [-1.70277810e-01, -5.33509861e-01],
       [-1.69391173e+00, -8.20012203e-01],
       [-1.37176443e+00, -7.60527560e-01],
       [ 4.98078619e+00,  6.36131598e-01],
       [-1.30680890e+00, -7.66729016e-01],
       [ 1.59289421e+00, -1.36470092e-01],
       [-1.39223597e+00, -7.48886300e-01],
       [-1.73914074e+00, -8.00615103e-01],
       [ 2.79175043e+00,  1.62110011e-01],
       [ 5.28653170e+00,  6.79350806e-01],
       [-1.56820383e+00, -7.64274959e-01],
       [-7.70084494e-01, -6.28900239e-01],
       [ 1.77734495e+00, -5.98068470e-02],
       [-1.45285128e+00, -7.88240146e-01],
       [-1.04533120e+00, -6.97157497e-01],
       [-1.52297482e+00, -7.83672060e-01],
       [-1.56610225e+00, -7.98345038e-01],
       [ 3.16972110e+00,  2.34202030e-01],
       [-1.63105778e+00, -7.92143581e-01],
       [-1.73912266e+00, -8.00700111e-01],
       [ 8.19480910e-01, -2.30230473e-01],
       [ 1.45793131e+00, -1.57175728e-01],
       [ 2.33494201e+00, -7.65213121e-03],
       [-1.21179082e+00, -7.56468089e-01],
       [-1.01009176e+00, -6.74991663e-01],
       [-1.46012087e+00, -7.55803438e-01],
       [ 3.88691335e+00,  4.02166001e-01],
       [-1.56816766e+00, -7.64444976e-01],
       [-9.52155665e-01, -6.68638689e-01],
       [ 3.25461478e+00,  1.06377961e-01],
       [-1.91007765e+00, -8.36955246e-01],
       [ 2.97935037e+00,  2.38234471e-01],
       [-1.62887343e+00, -7.54188083e-01],
       [-1.19872594e+00, -7.58257495e-01],
       [-1.56820383e+00, -7.64274959e-01],
       [-1.46012087e+00, -7.55803438e-01],
       [ 3.41530416e+00,  2.72730755e-01],
       [ 3.52405541e+00,  3.14857588e-01],
       [-1.73914074e+00, -8.00615103e-01],
       [-8.23971867e-01, -6.38261815e-01],
       [ 4.88258954e+00,  5.38317367e-01],
       [-1.73914074e+00, -8.00615103e-01],
       [-1.41837201e+00, -7.49951381e-01],
       [ 3.05316166e+00,  2.47005097e-01],
       [ 3.21084824e+00,  2.53874826e-01],
       [ 4.42092004e+00,  4.70276733e-01],
       [ 4.14262473e-01, -3.48891087e-01],
       [-1.30680890e+00, -7.66729016e-01],
       [ 1.06194212e+00, -2.81765466e-01],
       [ 3.30315664e+00,  3.56364145e-01],
       [ 1.29978163e+00, -1.38705903e-01],
       [ 2.36776338e+00,  9.08644849e-02],
       [-1.45508992e+00, -7.76754922e-01],
       [ 5.54342215e+00,  7.74640039e-01],
       [ 1.14819166e+00, -2.37003598e-01],
       [-1.46360102e+00, -7.30554281e-01],
       [-3.16036421e+00,  7.75351371e+00],
       [-1.69391173e+00, -8.20012203e-01],
       [-1.64484187e+00, -8.36326564e-01],
       [-1.31376920e+00, -7.16230703e-01],
       [-7.36939509e-01, -6.60487267e-01],
       [ 4.78680085e+00,  4.71813761e-01],
       [-1.73914074e+00, -8.00615103e-01],
       [-1.91007765e+00, -8.36955246e-01],
       [ 3.41530416e+00,  2.72730755e-01],
       [ 2.00758117e+00, -1.27785977e-01],
       [-1.51097660e+00, -7.33255098e-01],
       [-1.52297482e+00, -7.83672060e-01],
       [-5.70152506e-01, -5.83200078e-01],
       [ 2.59853628e+00,  1.66493909e-01],
       [ 1.16451411e+00, -1.48389080e-01],
       [-1.46012087e+00, -7.55803438e-01],
       [-1.58579260e+00, -8.11710698e-01],
       [-1.17607005e+00, -7.31943257e-01],
       [-1.14652966e+00, -7.06286149e-01],
       [-6.39052627e-01, -5.92310915e-01],
       [ 1.39014784e+00, -1.38490158e-01],
       [ 1.75327296e+00, -1.51898672e-01],
       [-1.30014726e+00, -7.51743967e-01],
       [-1.56820383e+00, -7.64274959e-01],
       [-1.46012087e+00, -7.55803438e-01],
       [-1.47774581e+00, -8.03069160e-01],
       [-1.34700696e+00, -7.68283400e-01],
       [-1.19361222e+00, -7.07183402e-01],
       [-1.91007765e+00, -8.36955246e-01],
       [-1.00513314e+00, -6.95603113e-01],
       [ 2.05214656e+00, -1.32012493e-01],
       [-1.64408649e+00, -7.90524193e-01],
       [-3.86961434e+00,  7.64074588e+00],
       [-1.62895620e+00, -8.26213659e-01],
       [-1.80199469e+00, -8.28483725e-01],
       [ 4.28384216e+00,  5.15786132e-01],
       [-4.98024921e-01, -5.33590261e-01],
       [-1.41489186e+00, -7.75200538e-01],
       [-1.24395495e+00, -7.38860395e-01],
       [-1.28074866e+00, -7.15822752e-01],
       [-1.67418521e+00, -8.06816559e-01],
       [-1.48122596e+00, -7.77820003e-01],
       [-1.52297482e+00, -7.83672060e-01],
       [-1.69391173e+00, -8.20012203e-01]])

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = []
for i in range(1,21):
           
    classifier = KNeighborsClassifier(n_neighbors=i)
    trained_model=classifier.fit(X_train,y_train)
    trained_model.fit(X_train,y_train )

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
cm_KNN = confusion_matrix(y_test, y_pred)
print(cm_KNN)
print("Accuracy score of train KNN")
print(accuracy_score(y_train, trained_model.predict(X_train))*100)
    
print("Accuracy score of test KNN")
print(accuracy_score(y_test, y_pred)*100)
    
knn.append(accuracy_score(y_test, y_pred)*100)

[[111   5]
 [  1  58]]
Accuracy score of train KNN
96.94656488549617
Accuracy score of test KNN
96.57142857142857

In [21]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)

trained_model=classifier.fit(X_train,y_train)
trained_model.fit(X_train,y_train )

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [22]:
y_pred = classifier.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix
cm_SVM = confusion_matrix(y_test, y_pred)
print(cm_SVM)
print("Accuracy score of train SVM")
print(accuracy_score(y_train, trained_model.predict(X_train))*100)

print("Accuracy score of test SVM")
print(accuracy_score(y_test, y_pred)*100)

[[111   5]
 [  1  58]]
Accuracy score of train SVM
95.99236641221374
Accuracy score of test SVM
96.57142857142857